# -*- coding: utf-8 -*-
"""scraping data komentar YT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wq6UY9V2kpNuo5Xe5SbGS15PdiTnwSEd
"""

!pip install youtube-comment-downloader

from youtube_comment_downloader import YoutubeCommentDownloader
import pandas as pd

# URL video YouTube
url = "https://youtu.be/4hzKmtEUF1I?si=kj-_R0gpC_7zOUlv"

# Membuat downloader
downloader = YoutubeCommentDownloader()

# Mengambil komentar
komentar = []

for comment in downloader.get_comments_from_url(url):
    komentar.append([
        comment['text'],
        comment['author'],
        comment['votes']
    ])

# Membuat DataFrame
df = pd.DataFrame(
    komentar,
    columns=["Komentar", "Username", "Like"]
)

# Menampilkan hasil
df.head()

df.to_csv("komentar_youtube.csv", index=False, encoding="utf-8-sig")

import os

os.listdir()

from google.colab import files

files.download("komentar_youtube.csv")

!pip install nlp-id

import pandas as pd

# Membaca data
df = pd.read_csv("komentar_youtube.csv")

# Kamus sederhana
positif = [
    "bagus", "baik", "mantap", "hebat",
    "membantu", "sukses", "senang",
    "setuju", "bermanfaat"
]

negatif = [
    "buruk", "jelek", "gagal", "kecewa",
    "mahal", "korupsi", "tidak setuju",
    "bohong", "masalah"
]


# Fungsi pelabelan
def label_sentimen(teks):
    teks = str(teks).lower()

    skor_pos = sum(kata in teks for kata in positif)
    skor_neg = sum(kata in teks for kata in negatif)

    if skor_pos > skor_neg:
        return "Positif"
    elif skor_neg > skor_pos:
        return "Negatif"
    else:
        return "Netral"


# Membuat kolom sentimen
df["Sentimen"] = df["Komentar"].apply(label_sentimen)

# Melihat hasil
df.head()

df.to_csv(
    "komentar_labeled.csv",
    index=False,
    encoding="utf-8-sig"
)

df.to_csv("komentar_labeled.csv", index=False, encoding="utf-8-sig")

from google.colab import files

files.download("komentar_labeled.csv")

df.head()

df["Sentimen"].value_counts()

!pip install Sastrawi

import pandas as pd
import numpy as np
import re
import string

# Preprocessing
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Evaluasi
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Visualisasi
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("komentar_labeled.csv")

# Melihat data
df.head()

df.isnull().sum()

def cleaning(teks):
    teks = str(teks)

    # Hapus URL
    teks = re.sub(r'http\S+|www\S+', '', teks)

    # Hapus mention dan hashtag
    teks = re.sub(r'@\w+|#\w+', '', teks)

    # Hapus angka
    teks = re.sub(r'\d+', '', teks)

    # Hapus karakter selain huruf
    teks = re.sub(r'[^A-Za-z\s]', '', teks)

    # Hapus spasi berlebih
    teks = re.sub(r'\s+', ' ', teks).strip()

    return teks

df['cleaning'] = df['Komentar'].apply(cleaning)

df[['Komentar', 'cleaning']].head()

df['case_folding'] = df['cleaning'].str.lower()

df[['cleaning', 'case_folding']].head()

def tokenisasi(teks):
    return teks.split()

df['token'] = df['case_folding'].apply(tokenisasi)

df[['case_folding', 'token']].head()

stopword = [
    'yang','dan','di','ke','dari','ini','itu',
    'untuk','dengan','pada','adalah','karena',
    'atau','juga','saya','kami','kita'
]


def hapus_stopword(tokens):
    hasil = []

    for kata in tokens:
        if kata not in stopword:
            hasil.append(kata)

    return hasil


df['stopword'] = df['token'].apply(hapus_stopword)

df[['token','stopword']].head()

factory = StemmerFactory()
stemmer = factory.create_stemmer()


def stemming(tokens):
    hasil = []

    for kata in tokens:
        hasil.append(stemmer.stem(kata))

    return " ".join(hasil)


df['stemming'] = df['stopword'].apply(stemming)

df[['stopword', 'stemming']].head()

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['stemming'])

y = df['Sentimen']

print("Jumlah fitur:", X.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

akurasi = accuracy_score(y_test, y_pred)

print("Akurasi Model:", akurasi)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=model.classes_,
    yticklabels=model.classes_
)

plt.xlabel("Prediksi")
plt.ylabel("Aktual")
plt.title("Confusion Matrix Naive Bayes")

plt.show()

df.to_csv(
    "hasil_preprocessing.csv",
    index=False,
    encoding="utf-8-sig"
)

from google.colab import files

files.download("hasil_preprocessing.csv")